config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users

  resources :groups, only: [:index, :new, :create], path: "categories" do
    resources :purchases, only: [:index, :show, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :group_purchases, dependent: :destroy
  has_many :purchases, through: :group_purchases, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true

  # Returns the total amount of all purchases in the group
  def total
    purchases.sum(:amount)
  end
end

app/models/group_purchase.rb
class GroupPurchase < ApplicationRecord
  self.table_name = 'group_purchases_tables'
  belongs_to :group
  belongs_to :purchase
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :group_purchases, dependent: :destroy
  has_many :groups, through: :group_purchases, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
  validates :groups, presence: true
  validates :author_id, presence: true

  private

  def at_least_one_group
    errors.add(:groups, 'must be selected') if groups.empty?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchases, foreign_key: 'author_id'
  has_many :groups, foreign_key: 'author_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.includes(:purchases).order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to groups_path
    else
      render 'pages/home'
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  def index
    @purchases = @group.purchases.order(created_at: :desc)
    @total_amount = @group.total
  end

  def new
    @user = current_user
    @purchase = @user.purchases.build
    @groups = @user.groups
  end

  def create
    @purchase = current_user.purchases.new(purchase_params)
    @groups = current_user.groups
    if @purchase.save
      redirect_to group_purchases_path(@group), notice: 'Purchase was successfully added.'
    else
      render :new
    end
  end

  private

  def set_group
    @group = current_user.groups.includes(:purchases).find(params[:group_id])
  end

  def purchase_params
    params.require(:purchase).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])

    return unless @user.nil?

    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<%= render partial: "shared/navbar", locals: { title: "Categories", logout: true, back_path: groups_path } %>

<div id="groups">
  <% @groups.each do |group| %>
    <%= link_to group_purchases_path(group) do %>
      <div class="grid grid-cols-4 gap-1 m-2 border-2 border-grey bg-white p-2 items-center">
        <div class="col-span-1">
          <img src=<%=group.icon%> class="w-full h-24 object-cover border-2 rounded border-black">
        </div>
        <div class="col-span-2 flex flex-col -mx-10 justify-between p-4">
          <p><%= group.name %></p>
          <p><%= group.created_at.strftime("%d/%m/%Y") %></p>
        </div>
        <div class="col-span-1 p-4 font-bold">
          <p><%= group.total %>$</p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to new_group_path, class:"fixed inset-x-0 bottom-0 bg-[#5fb523] p-5 text-center text-white hover:bg-[#55a01f]" do%>
  <div class="p-2 border border-white">
    New Category
  </div>
<% end %>

app/views/groups/new.html.erb
<%= render partial: "shared/navbar", locals: { title: "New Category", logout: false, back_path: groups_path } %>

<div class="w-full flex flex-col space-y-4">
  <%= form_with(model: @group, url: groups_path, local: true, method: :post) do |f| %>  
    <div class="w-full">
      <%= f.text_field :name, autocomplete: "off", placeholder:"Category Name", class: "shadow appearance-none border w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="w-full">
      <%= f.text_field :icon, autocomplete: "off", placeholder:"Category Icon", class: "shadow appearance-none border w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="w-full fixed inset-x-0 bottom-0 bg-[#5fb523] p-5 text-center text-white hover:bg-[#55a01f]">
      <div class="p-2 border border-white">
        <%= f.submit "Create Category", class: "button" %>
      <div>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<nav class="bg-blue-700 p-4 relative">
  <div class="container mx-auto flex items-center justify-between">
    <div>
      <%= link_to "Back to groups", groups_path %>
    </div>

    <div> 
      <h2>Transactions</h2>
    </div>

    <div>
      <img src="https://www.pngall.com/wp-content/uploads/13/Search-Button-White-PNG.png" alt="search"  width="50" height="80">
    </div>
  </div>
</nav>

<%= link_to "New transaction", new_group_purchase_path(@group)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="font-montserrat bg-gray-200 transition-all duration-150">
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex items-center justify-center min-h-screen font-semibold">
  <div class="text-4xl text-center">
    <h1>Salty Budget</h1>
  </div>
</div>
<div class="fixed inset-x-0 bottom-5 flex flex-col items-center">
  <%= link_to new_user_session_path do %>
    <div class="w-96 p-4 text-center hover:bg-[#3778c2] hover:text-white">
      LOG IN
    </div>
  <% end %> 
  <%= link_to new_user_registration_path do%>
    <div class="w-96 p-4 text-center hover:bg-[#3778c2] hover:text-white">
      SIGN UP
    </div>
  <% end %>
</div>

app/views/purchases/index.html.erb
<%= render partial: "shared/navbar", locals: { title: "Transactions", logout: false, back_path: groups_path } %>

<div id="purchases">
  <% @purchases.each do |purchase| %>
    <div class="grid grid-cols-4 gap-1 m-2 border-2 border-grey bg-white p-2 items-center">
      <div class="col-span-1">
        <img src=<%=@group.icon%> class="w-full h-24 object-cover border-2 rounded border-black">
      </div>
      <div class="col-span-2 -mx-10 flex flex-col p-4">
        <p><%= purchase.name %></p>
        <p><%= purchase.created_at.strftime("%d/%m/%Y") %></p>
      </div>
      <div class="col-span-1 p-4 font-bold">
        <p><%= purchase.amount %>$</p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to new_group_purchase_path(@group), class:"fixed inset-x-0 bottom-0 bg-[#5fb523] p-5 text-center text-white hover:bg-[#55a01f]" do%>
  <div class="p-2 border border-white">
    New Transaction
  </div>
<% end %>

app/views/purchases/new.html.erb
<%= render partial: "shared/navbar", locals: { title: "Add Transaction", logout: false, back_path: group_purchases_path } %>

<div class="w-full flex flex-col space-y-4">
  <%= form_with(model: @purchase, url: group_purchases_path, local: true, method: :post) do |f| %>  
    
    <div class="w-full">
      <%= f.text_field :name, autocomplete: "off", placeholder:"Transaction Name", class: "shadow appearance-none border w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="w-full">
      <%= f.number_field :amount, in: 1..10000, step: 0.01, autocomplete: "off", placeholder:"Amount", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="w-full"> 
        <% @groups.each do |group| %>
            <%= check_box_tag 'purchase[group_ids][]', group.id, @purchase.group_ids.include?(group.id), id: dom_id(group) %>
            <%= label_tag dom_id(group), group.name %>
        <% end %>
    </div>

    <div class="w-full fixed inset-x-0 bottom-0 bg-[#5fb523] p-5 text-center text-white hover:bg-[#55a01f]">
      <div class="p-2 border border-white">
        <%= f.submit "Create Transaction", class: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-blue-700 p-4 relative">
  <div class="container mx-auto flex items-center justify-between">
    <div>
      <% if logout %>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class:"text-white" %>
      <% else %>
        <%= link_to back_path do %>
          <%= image_tag("https://www.pinclipart.com/picdir/big/544-5440422_back-arrow-icon-transparent-png-clipart-free-download.png", alt: "Back", class:"max-h-10 invert") %>
        <% end %>
      <% end %>
    </div>

    <div class="text-white text-lg"> 
      <h2><%= title %></h2>
    </div>

    <div>
      <img src="https://www.pngall.com/wp-content/uploads/13/Search-Button-White-PNG.png" alt="search"  width="50" height="80">
    </div>
  </div>
</nav>